from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

def create_pdf(filename):
    c = canvas.Canvas(filename, pagesize=letter)
    width, height = letter

    # Title
    c.setFont("Helvetica-Bold", 24)
    c.drawString(50, height - 50, "Executive Summary: Dynamic Pricing Strategy")
    
    # Subtitle
    c.setFont("Helvetica", 12)
    c.drawString(50, height - 80, "Optimizing Revenue through Machine Learning & Econometrics")
    c.line(50, height - 90, 550, height - 90)

    # Section 1: Objective
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 130, "1. Objective")
    c.setFont("Helvetica", 11)
    text = "To build a data-driven pricing engine that forecasts demand and recommends optimal"
    c.drawString(50, height - 150, text)
    text = "price points to maximize revenue, replacing gut-feel decisions with algorithmic precision."
    c.drawString(50, height - 165, text)

    # Section 2: Methodology
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 200, "2. Methodology")
    c.setFont("Helvetica", 11)
    c.drawString(60, height - 220, "- Data Ingestion: Processed 15,000+ transaction records with seasonality injection.")
    c.drawString(60, height - 235, "- Modeling: Used Log-Log Regression for elasticity and Random Forest for forecasting.")
    c.drawString(60, height - 250, "- Optimization: Grid-search algorithm to identify revenue-maximizing price points.")

    # Section 3: Key Findings
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 290, "3. Key Findings (The 'Aha!' Moment)")
    c.setFont("Helvetica", 11)
    c.drawString(60, height - 310, "• Price Elasticity: +0.11 (Inelastic/Veblen Good Behavior).")
    c.drawString(60, height - 325, "• Insight: Customers in this segment associate higher prices with quality.")
    c.drawString(60, height - 340, "• Driver Analysis: Ad Spend and Promotion Intensity are 3x more impactful than Price.")
    
    # Section 4: Recommendations
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 380, "4. Strategic Recommendations")
    c.setFont("Helvetica", 11)
    c.drawString(60, height - 400, "1. HOLD PREMIUM PRICING: Do not discount aggressively. The data shows it does")
    c.drawString(75, height - 415, "not significantly drive volume.")
    c.drawString(60, height - 435, "2. OPTIMIZE AD SPEND: Reallocate budget from discounts to high-intensity ad campaigns.")
    c.drawString(60, height - 455, "3. USE THE DASHBOARD: Utilize the delivered Streamlit tool to simulate competitor")
    c.drawString(75, height - 470, "responses before changing prices.")

    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 50, "Generated by Dynamic Pricing Engine | Partnr Submission")
    
    c.save()
    print(f"PDF Report generated successfully: {filename}")

if __name__ == "__main__":
    # Save directly to the reports folder
    create_pdf("reports/executive_summary.pdf")